// src/utils/categoriesData.js
// Default categories with placeholder image URLs (online sources for demo)
// In production, replace with local assets

import LOCAL_IMAGES from './localImages';

const withLocalImages = (categoryKey, images) => {
  const localImages = LOCAL_IMAGES[categoryKey];

  if (!Array.isArray(localImages) || localImages.length === 0) {
    return images;
  }

  return images.map((image, index) => ({
    ...image,
    source: localImages[index] || image.source,
  }));
};

export const DEFAULT_CATEGORIES = [
  {
    id: 'devotional',
    name: 'Devotional Swamy',
    icon: '🕉️',
    color: '#FF6B35',
    gradientColors: ['#FF6B35', '#FF8C42'],
    totalPuzzles: 15,
    musicKey: 'devotional',
    images: withLocalImages('devotional', [
      { id: 'dev_1', name: 'Ganesha', uri: 'https://picsum.photos/seed/ganesha/400/400' },
      { id: 'dev_2', name: 'Krishna', uri: 'https://picsum.photos/seed/krishna/400/400' },
      { id: 'dev_3', name: 'Shiva', uri: 'https://picsum.photos/seed/shiva1/400/400' },
      { id: 'dev_4', name: 'Lakshmi', uri: 'https://picsum.photos/seed/lakshmi/400/400' },
      { id: 'dev_5', name: 'Saraswati', uri: 'https://picsum.photos/seed/saras/400/400' },
      { id: 'dev_6', name: 'Murugan', uri: 'https://picsum.photos/seed/murugan/400/400' },
      { id: 'dev_7', name: 'Hanuman', uri: 'https://picsum.photos/seed/hanuman/400/400' },
      { id: 'dev_8', name: 'Durga', uri: 'https://picsum.photos/seed/durga1/400/400' },
      { id: 'dev_9', name: 'Vishnu', uri: 'https://picsum.photos/seed/vishnu1/400/400' },
      { id: 'dev_10', name: 'Balaji', uri: 'https://picsum.photos/seed/balaji/400/400' },
    ]),
  },
  {
    id: 'actors',
    name: 'Actor Images',
    icon: '🎬',
    color: '#6C63FF',
    gradientColors: ['#6C63FF', '#8B85FF'],
    totalPuzzles: 15,
    musicKey: 'actors',
    images: withLocalImages('actors', [
      { id: 'act_1', name: 'Actor 1', uri: 'https://picsum.photos/seed/actor1/400/400', musicKey: '1' },
      { id: 'act_2', name: 'Actor 2', uri: 'https://picsum.photos/seed/actor2/400/400', musicKey: '2' },
      { id: 'act_3', name: 'Actor 3', uri: 'https://picsum.photos/seed/actor3/400/400', musicKey: '3' },
      { id: 'act_4', name: 'Actor 4', uri: 'https://picsum.photos/seed/actor4/400/400', musicKey: '4' },
      { id: 'act_5', name: 'Actor 5', uri: 'https://picsum.photos/seed/actor5/400/400', musicKey: '5' },
      { id: 'act_6', name: 'Actor 6', uri: 'https://picsum.photos/seed/actor6/400/400', musicKey: '6' },
      { id: 'act_7', name: 'Actor 7', uri: 'https://picsum.photos/seed/actor7/400/400', musicKey: '7' },
      { id: 'act_8', name: 'Actor 8', uri: 'https://picsum.photos/seed/actor8/400/400', musicKey: '8' },
      { id: 'act_9', name: 'Actor 9', uri: 'https://picsum.photos/seed/actor9/400/400', musicKey: '9' },
      { id: 'act_10', name: 'Actor 10', uri: 'https://picsum.photos/seed/actor10/400/400', musicKey: '10' },
    ]),
  },
  {
    id: 'actresses',
    name: 'Actress Images',
    icon: '🌟',
    color: '#E91E63',
    gradientColors: ['#E91E63', '#F06292'],
    totalPuzzles: 15,
    musicKey: 'actresses',
    images: withLocalImages('actresses', [
      { id: 'actr_1', name: 'Actress 1', uri: 'https://picsum.photos/seed/actress1/400/400' },
      { id: 'actr_2', name: 'Actress 2', uri: 'https://picsum.photos/seed/actress2/400/400' },
      { id: 'actr_3', name: 'Actress 3', uri: 'https://picsum.photos/seed/actress3/400/400' },
      { id: 'actr_4', name: 'Actress 4', uri: 'https://picsum.photos/seed/actress4/400/400' },
      { id: 'actr_5', name: 'Actress 5', uri: 'https://picsum.photos/seed/actress5/400/400' },
      { id: 'actr_6', name: 'Actress 6', uri: 'https://picsum.photos/seed/actress6/400/400' },
      { id: 'actr_7', name: 'Actress 7', uri: 'https://picsum.photos/seed/actress7/400/400' },
      { id: 'actr_8', name: 'Actress 8', uri: 'https://picsum.photos/seed/actress8/400/400' },
      { id: 'actr_9', name: 'Actress 9', uri: 'https://picsum.photos/seed/actress9/400/400' },
      { id: 'actr_10', name: 'Actress 10', uri: 'https://picsum.photos/seed/actress10/400/400' },
    ]),
  },
  {
    id: 'fruits',
    name: 'Fruit Images',
    icon: '🍎',
    color: '#4CAF50',
    gradientColors: ['#2E7D32', '#66BB6A'],
    totalPuzzles: 15,
    musicKey: 'fruits',
    images: withLocalImages('fruits', [
      { id: 'fr_1', name: 'Apple', uri: 'https://picsum.photos/seed/apple1/400/400' },
      { id: 'fr_2', name: 'Mango', uri: 'https://picsum.photos/seed/mango1/400/400' },
      { id: 'fr_3', name: 'Banana', uri: 'https://picsum.photos/seed/banana1/400/400' },
      { id: 'fr_4', name: 'Orange', uri: 'https://picsum.photos/seed/orange1/400/400' },
      { id: 'fr_5', name: 'Grapes', uri: 'https://picsum.photos/seed/grapes1/400/400' },
      { id: 'fr_6', name: 'Watermelon', uri: 'https://picsum.photos/seed/waterme/400/400' },
      { id: 'fr_7', name: 'Pineapple', uri: 'https://picsum.photos/seed/pineapp/400/400' },
      { id: 'fr_8', name: 'Strawberry', uri: 'https://picsum.photos/seed/strawb/400/400' },
      { id: 'fr_9', name: 'Papaya', uri: 'https://picsum.photos/seed/papaya1/400/400' },
      { id: 'fr_10', name: 'Guava', uri: 'https://picsum.photos/seed/guava1/400/400' },
    ]),
  },
  {
    id: 'food',
    name: 'Food Images',
    icon: '🍛',
    color: '#FF9800',
    gradientColors: ['#E65100', '#FFA726'],
    totalPuzzles: 15,
    musicKey: 'food',
    images: withLocalImages('food', [
      { id: 'food_1', name: 'Biryani', uri: 'https://picsum.photos/seed/biryani/400/400' },
      { id: 'food_2', name: 'Dosa', uri: 'https://picsum.photos/seed/dosa123/400/400' },
      { id: 'food_3', name: 'Idli', uri: 'https://picsum.photos/seed/idli123/400/400' },
      { id: 'food_4', name: 'Pizza', uri: 'https://picsum.photos/seed/pizza12/400/400' },
      { id: 'food_5', name: 'Burger', uri: 'https://picsum.photos/seed/burger1/400/400' },
      { id: 'food_6', name: 'Samosa', uri: 'https://picsum.photos/seed/samosa/400/400' },
      { id: 'food_7', name: 'Cake', uri: 'https://picsum.photos/seed/cake123/400/400' },
      { id: 'food_8', name: 'Ice Cream', uri: 'https://picsum.photos/seed/icecre/400/400' },
      { id: 'food_9', name: 'Noodles', uri: 'https://picsum.photos/seed/noodle/400/400' },
      { id: 'food_10', name: 'Sweets', uri: 'https://picsum.photos/seed/sweet1/400/400' },
    ]),
  },
  {
    id: 'animals',
    name: 'Animal Images',
    icon: '🦁',
    color: '#795548',
    gradientColors: ['#4E342E', '#8D6E63'],
    totalPuzzles: 15,
    musicKey: 'animals',
    images: withLocalImages('animals', [
      { id: 'ani_1', name: 'Lion', uri: 'https://picsum.photos/seed/lion123/400/400' },
      { id: 'ani_2', name: 'Tiger', uri: 'https://picsum.photos/seed/tiger1/400/400' },
      { id: 'ani_3', name: 'Elephant', uri: 'https://picsum.photos/seed/eleph/400/400' },
      { id: 'ani_4', name: 'Giraffe', uri: 'https://picsum.photos/seed/giraf/400/400' },
      { id: 'ani_5', name: 'Zebra', uri: 'https://picsum.photos/seed/zebra1/400/400' },
      { id: 'ani_6', name: 'Monkey', uri: 'https://picsum.photos/seed/monkey/400/400' },
      { id: 'ani_7', name: 'Parrot', uri: 'https://picsum.photos/seed/parrot/400/400' },
      { id: 'ani_8', name: 'Peacock', uri: 'https://picsum.photos/seed/peacok/400/400' },
      { id: 'ani_9', name: 'Deer', uri: 'https://picsum.photos/seed/deer12/400/400' },
      { id: 'ani_10', name: 'Rabbit', uri: 'https://picsum.photos/seed/rabbit/400/400' },
    ]),
  },
  {
    id: 'nature',
    name: 'Nature Images',
    icon: '🌿',
    color: '#009688',
    gradientColors: ['#00695C', '#26A69A'],
    totalPuzzles: 15,
    musicKey: 'nature',
    images: withLocalImages('nature', [
      { id: 'nat_1', name: 'Mountain', uri: 'https://picsum.photos/seed/mount1/400/400' },
      { id: 'nat_2', name: 'Waterfall', uri: 'https://picsum.photos/seed/waterf/400/400' },
      { id: 'nat_3', name: 'Sunrise', uri: 'https://picsum.photos/seed/sunris/400/400' },
      { id: 'nat_4', name: 'Forest', uri: 'https://picsum.photos/seed/forest/400/400' },
      { id: 'nat_5', name: 'Beach', uri: 'https://picsum.photos/seed/beach1/400/400' },
      { id: 'nat_6', name: 'Flowers', uri: 'https://picsum.photos/seed/flower/400/400' },
      { id: 'nat_7', name: 'River', uri: 'https://picsum.photos/seed/river1/400/400' },
      { id: 'nat_8', name: 'Desert', uri: 'https://picsum.photos/seed/desert/400/400' },
      { id: 'nat_9', name: 'Rainbow', uri: 'https://picsum.photos/seed/rainb1/400/400' },
      { id: 'nat_10', name: 'Snow', uri: 'https://picsum.photos/seed/snow12/400/400' },
    ]),
  },
  {
    id: 'cartoons',
    name: 'Cartoon Images',
    icon: '🐭',
    color: '#FFEB3B',
    gradientColors: ['#F57F17', '#FFCA28'],
    totalPuzzles: 15,
    musicKey: 'cartoons',
    images: withLocalImages('cartoons', [
      { id: 'car_1', name: 'Mickey', uri: 'https://picsum.photos/seed/micke1/400/400' },
      { id: 'car_2', name: 'Tom & Jerry', uri: 'https://picsum.photos/seed/tomjer/400/400' },
      { id: 'car_3', name: 'Doraemon', uri: 'https://picsum.photos/seed/dorae1/400/400' },
      { id: 'car_4', name: 'Minions', uri: 'https://picsum.photos/seed/minion/400/400' },
      { id: 'car_5', name: 'SpongeBob', uri: 'https://picsum.photos/seed/spong1/400/400' },
      { id: 'car_6', name: 'Shinchan', uri: 'https://picsum.photos/seed/shinch/400/400' },
      { id: 'car_7', name: 'Chhota Bheem', uri: 'https://picsum.photos/seed/bheem1/400/400' },
      { id: 'car_8', name: 'Simba', uri: 'https://picsum.photos/seed/simba1/400/400' },
      { id: 'car_9', name: 'Pikachu', uri: 'https://picsum.photos/seed/pikac1/400/400' },
      { id: 'car_10', name: 'Winnie Pooh', uri: 'https://picsum.photos/seed/winnie/400/400' },
    ]),
  },
  {
    id: 'festivals',
    name: 'Festival Images',
    icon: '🎊',
    color: '#9C27B0',
    gradientColors: ['#6A1B9A', '#AB47BC'],
    totalPuzzles: 15,
    musicKey: 'festivals',
    images: withLocalImages('festivals', [
      { id: 'fes_1', name: 'Diwali', uri: 'https://picsum.photos/seed/diwali/400/400' },
      { id: 'fes_2', name: 'Holi', uri: 'https://picsum.photos/seed/holi12/400/400' },
      { id: 'fes_3', name: 'Pongal', uri: 'https://picsum.photos/seed/pongal/400/400' },
      { id: 'fes_4', name: 'Christmas', uri: 'https://picsum.photos/seed/xmas12/400/400' },
      { id: 'fes_5', name: 'Eid', uri: 'https://picsum.photos/seed/eid123/400/400' },
      { id: 'fes_6', name: 'Navratri', uri: 'https://picsum.photos/seed/navrat/400/400' },
      { id: 'fes_7', name: 'Onam', uri: 'https://picsum.photos/seed/onam12/400/400' },
      { id: 'fes_8', name: 'Ganesh Chaturthi', uri: 'https://picsum.photos/seed/ganesh/400/400' },
      { id: 'fes_9', name: 'Durga Puja', uri: 'https://picsum.photos/seed/durga2/400/400' },
      { id: 'fes_10', name: 'New Year', uri: 'https://picsum.photos/seed/newyar/400/400' },
    ]),
  },
  {
    id: 'kids',
    name: 'Kids Images',
    icon: '👶',
    color: '#03A9F4',
    gradientColors: ['#01579B', '#29B6F6'],
    totalPuzzles: 15,
    musicKey: 'kids',
    images: withLocalImages('kids', [
      { id: 'kid_1', name: 'Playing', uri: 'https://picsum.photos/seed/kidpl1/400/400' },
      { id: 'kid_2', name: 'Drawing', uri: 'https://picsum.photos/seed/kiddr1/400/400' },
      { id: 'kid_3', name: 'Cycling', uri: 'https://picsum.photos/seed/kidcy1/400/400' },
      { id: 'kid_4', name: 'Reading', uri: 'https://picsum.photos/seed/kidre1/400/400' },
      { id: 'kid_5', name: 'Dancing', uri: 'https://picsum.photos/seed/kidda1/400/400' },
      { id: 'kid_6', name: 'Swimming', uri: 'https://picsum.photos/seed/kidsw1/400/400' },
      { id: 'kid_7', name: 'Football', uri: 'https://picsum.photos/seed/kidfo1/400/400' },
      { id: 'kid_8', name: 'Birthday', uri: 'https://picsum.photos/seed/kidbi1/400/400' },
      { id: 'kid_9', name: 'School', uri: 'https://picsum.photos/seed/kidsc1/400/400' },
      { id: 'kid_10', name: 'Garden', uri: 'https://picsum.photos/seed/kidga1/400/400' },
    ]),
  },
];
