const LOCAL_IMAGES = {
  devotional: [
    require('../../assets/categories/devotional/1.jpg'),
    require('../../assets/categories/devotional/2.jpg'),
    require('../../assets/categories/devotional/3.jpg'),
    require('../../assets/categories/devotional/4.jpg'),
    require('../../assets/categories/devotional/5.jpg'),
    require('../../assets/categories/devotional/6.jpg'),
    require('../../assets/categories/devotional/7.jpg'),
    require('../../assets/categories/devotional/8.jpg'),
    require('../../assets/categories/devotional/9.jpg'),
    require('../../assets/categories/devotional/10.jpg'),
  ],
  actors: [
    require('../../assets/categories/actors/1.jpg'),
    require('../../assets/categories/actors/2.jpg'),
    require('../../assets/categories/actors/3.jpg'),
    require('../../assets/categories/actors/4.jpg'),
    require('../../assets/categories/actors/5.jpg'),
    require('../../assets/categories/actors/6.jpg'),
    require('../../assets/categories/actors/7.jpg'),
    require('../../assets/categories/actors/8.jpg'),
    require('../../assets/categories/actors/9.jpg'),
    require('../../assets/categories/actors/10.jpg'),
  ],
  actresses: [
    require('../../assets/categories/actresses/1.jpg'),
    require('../../assets/categories/actresses/2.jpg'),
    require('../../assets/categories/actresses/3.jpg'),
    require('../../assets/categories/actresses/4.jpg'),
    require('../../assets/categories/actresses/5.jpg'),
    require('../../assets/categories/actresses/6.jpg'),
    require('../../assets/categories/actresses/7.jpg'),
    require('../../assets/categories/actresses/8.jpg'),
    require('../../assets/categories/actresses/9.jpg'),
    require('../../assets/categories/actresses/10.jpg'),
  ],
  fruits: [
    require('../../assets/categories/fruits/1.jpg'),
    require('../../assets/categories/fruits/2.jpg'),
    require('../../assets/categories/fruits/3.jpg'),
    require('../../assets/categories/fruits/4.jpg'),
    require('../../assets/categories/fruits/5.jpg'),
    require('../../assets/categories/fruits/6.jpg'),
    require('../../assets/categories/fruits/7.jpg'),
    require('../../assets/categories/fruits/8.jpg'),
    require('../../assets/categories/fruits/9.jpg'),
    require('../../assets/categories/fruits/10.jpg'),
  ],
  food: [
    require('../../assets/categories/food/1.jpg'),
    require('../../assets/categories/food/2.jpg'),
    require('../../assets/categories/food/3.jpg'),
    require('../../assets/categories/food/4.jpg'),
    require('../../assets/categories/food/5.jpg'),
    require('../../assets/categories/food/6.jpg'),
    require('../../assets/categories/food/7.jpg'),
    require('../../assets/categories/food/8.jpg'),
    require('../../assets/categories/food/9.jpg'),
    require('../../assets/categories/food/10.jpg'),
  ],
  animals: [
    require('../../assets/categories/animals/1.jpg'),
    require('../../assets/categories/animals/2.jpg'),
    require('../../assets/categories/animals/3.jpg'),
    require('../../assets/categories/animals/4.jpg'),
    require('../../assets/categories/animals/5.jpg'),
    require('../../assets/categories/animals/6.jpg'),
    require('../../assets/categories/animals/7.jpg'),
    require('../../assets/categories/animals/8.jpg'),
    require('../../assets/categories/animals/9.jpg'),
    require('../../assets/categories/animals/10.jpg'),
  ],
  nature: [
    require('../../assets/categories/nature/1.jpg'),
    require('../../assets/categories/nature/2.jpg'),
    require('../../assets/categories/nature/3.jpg'),
    require('../../assets/categories/nature/4.jpg'),
    require('../../assets/categories/nature/5.jpg'),
    require('../../assets/categories/nature/6.jpg'),
    require('../../assets/categories/nature/7.jpg'),
    require('../../assets/categories/nature/8.jpg'),
    require('../../assets/categories/nature/9.jpg'),
    require('../../assets/categories/nature/10.jpg'),
  ],
  cartoons: [
    require('../../assets/categories/cartoons/1.jpg'),
    require('../../assets/categories/cartoons/2.jpg'),
    require('../../assets/categories/cartoons/3.jpg'),
    require('../../assets/categories/cartoons/4.jpg'),
    require('../../assets/categories/cartoons/5.jpg'),
    require('../../assets/categories/cartoons/6.jpg'),
    require('../../assets/categories/cartoons/7.jpg'),
    require('../../assets/categories/cartoons/8.jpg'),
    require('../../assets/categories/cartoons/9.jpg'),
    require('../../assets/categories/cartoons/10.jpg'),
  ],
  festivals: [
    require('../../assets/categories/festivals/1.jpg'),
    require('../../assets/categories/festivals/2.jpg'),
    require('../../assets/categories/festivals/3.jpg'),
    require('../../assets/categories/festivals/4.jpg'),
    require('../../assets/categories/festivals/5.jpg'),
    require('../../assets/categories/festivals/6.jpg'),
    require('../../assets/categories/festivals/7.jpg'),
    require('../../assets/categories/festivals/8.jpg'),
    require('../../assets/categories/festivals/9.jpg'),
    require('../../assets/categories/festivals/10.jpg'),
  ],
  kids: [
    require('../../assets/categories/kids/1.jpg'),
    require('../../assets/categories/kids/2.jpg'),
    require('../../assets/categories/kids/3.jpg'),
    require('../../assets/categories/kids/4.jpg'),
    require('../../assets/categories/kids/5.jpg'),
    require('../../assets/categories/kids/6.jpg'),
    require('../../assets/categories/kids/7.jpg'),
    require('../../assets/categories/kids/8.jpg'),
    require('../../assets/categories/kids/9.jpg'),
    require('../../assets/categories/kids/10.jpg'),
  ],
};

export default LOCAL_IMAGES;
