const LOCAL_IMAGES = {
  devotional: [
    require('../../assets/categories/devotional/1.webp'),
    require('../../assets/categories/devotional/2.webp'),
    require('../../assets/categories/devotional/3.webp'),
    require('../../assets/categories/devotional/4.webp'),
    require('../../assets/categories/devotional/5.webp'),
    require('../../assets/categories/devotional/6.webp'),
    require('../../assets/categories/devotional/7.webp'),
    require('../../assets/categories/devotional/8.webp'),
    require('../../assets/categories/devotional/9.webp'),
    require('../../assets/categories/devotional/10.webp'),
  ],
  actors: [
    require('../../assets/categories/actors/1.webp'),
    require('../../assets/categories/actors/2.webp'),
    require('../../assets/categories/actors/3.webp'),
    require('../../assets/categories/actors/4.webp'),
    require('../../assets/categories/actors/5.webp'),
    require('../../assets/categories/actors/6.webp'),
    require('../../assets/categories/actors/7.webp'),
    require('../../assets/categories/actors/8.webp'),
    require('../../assets/categories/actors/9.webp'),
    require('../../assets/categories/actors/10.webp'),
  ],
  actresses: [
    require('../../assets/categories/actresses/1.webp'),
    require('../../assets/categories/actresses/2.webp'),
    require('../../assets/categories/actresses/3.webp'),
    require('../../assets/categories/actresses/4.webp'),
    require('../../assets/categories/actresses/5.webp'),
    require('../../assets/categories/actresses/6.webp'),
    require('../../assets/categories/actresses/7.webp'),
    require('../../assets/categories/actresses/8.webp'),
    require('../../assets/categories/actresses/9.webp'),
    require('../../assets/categories/actresses/10.webp'),
  ],
  fruits: [
    require('../../assets/categories/fruits/1.webp'),
    require('../../assets/categories/fruits/2.webp'),
    require('../../assets/categories/fruits/3.webp'),
    require('../../assets/categories/fruits/4.webp'),
    require('../../assets/categories/fruits/5.webp'),
    require('../../assets/categories/fruits/6.webp'),
    require('../../assets/categories/fruits/7.webp'),
    require('../../assets/categories/fruits/8.webp'),
    require('../../assets/categories/fruits/9.webp'),
    require('../../assets/categories/fruits/10.webp'),
  ],
  food: [
    require('../../assets/categories/food/1.webp'),
    require('../../assets/categories/food/2.webp'),
    require('../../assets/categories/food/3.webp'),
    require('../../assets/categories/food/4.webp'),
    require('../../assets/categories/food/5.webp'),
    require('../../assets/categories/food/6.webp'),
    require('../../assets/categories/food/7.webp'),
    require('../../assets/categories/food/8.webp'),
    require('../../assets/categories/food/9.webp'),
    require('../../assets/categories/food/10.webp'),
  ],
  animals: [
    require('../../assets/categories/animals/1.webp'),
    require('../../assets/categories/animals/2.webp'),
    require('../../assets/categories/animals/3.webp'),
    require('../../assets/categories/animals/4.webp'),
    require('../../assets/categories/animals/5.webp'),
    require('../../assets/categories/animals/6.webp'),
    require('../../assets/categories/animals/7.webp'),
    require('../../assets/categories/animals/8.webp'),
    require('../../assets/categories/animals/9.webp'),
    require('../../assets/categories/animals/10.webp'),
  ],
  nature: [
    require('../../assets/categories/nature/1.webp'),
    require('../../assets/categories/nature/2.webp'),
    require('../../assets/categories/nature/3.webp'),
    require('../../assets/categories/nature/4.webp'),
    require('../../assets/categories/nature/5.webp'),
    require('../../assets/categories/nature/6.webp'),
    require('../../assets/categories/nature/7.webp'),
    require('../../assets/categories/nature/8.webp'),
    require('../../assets/categories/nature/9.webp'),
    require('../../assets/categories/nature/10.webp'),
  ],
  cartoons: [
    require('../../assets/categories/cartoons/1.webp'),
    require('../../assets/categories/cartoons/2.webp'),
    require('../../assets/categories/cartoons/3.webp'),
    require('../../assets/categories/cartoons/4.webp'),
    require('../../assets/categories/cartoons/5.webp'),
    require('../../assets/categories/cartoons/6.webp'),
    require('../../assets/categories/cartoons/7.webp'),
    require('../../assets/categories/cartoons/8.webp'),
    require('../../assets/categories/cartoons/9.webp'),
    require('../../assets/categories/cartoons/10.webp'),
  ],
  festivals: [
    require('../../assets/categories/festivals/1.webp'),
    require('../../assets/categories/festivals/2.webp'),
    require('../../assets/categories/festivals/3.webp'),
    require('../../assets/categories/festivals/4.webp'),
    require('../../assets/categories/festivals/5.webp'),
    require('../../assets/categories/festivals/6.webp'),
    require('../../assets/categories/festivals/7.webp'),
    require('../../assets/categories/festivals/8.webp'),
    require('../../assets/categories/festivals/9.webp'),
    require('../../assets/categories/festivals/10.webp'),
  ],
  kids: [
    require('../../assets/categories/kids/1.webp'),
    require('../../assets/categories/kids/2.webp'),
    require('../../assets/categories/kids/3.webp'),
    require('../../assets/categories/kids/4.webp'),
    require('../../assets/categories/kids/5.webp'),
    require('../../assets/categories/kids/6.webp'),
    require('../../assets/categories/kids/7.webp'),
    require('../../assets/categories/kids/8.webp'),
    require('../../assets/categories/kids/9.webp'),
    require('../../assets/categories/kids/10.webp'),
  ],
};

export default LOCAL_IMAGES;
